### ISSUE TITLE
update bliss to 0.77

### ISSUE THREAD

**Issue by dimpase** [conda-forge/bliss-feedstock#4]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

bliss 0.73, currently shipped by Conda, is very old. There is now version 0.77 around, which can be built with cmake and a minimal patch (at Gentoo, for instance). SageMath is switching to 0.77, see
https://github.com/sagemath/sage/pull/35344 and
https://github.com/sagemath/sage/issues/35829

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by isuruf** [comment]
Updated in https://github.com/conda-forge/bliss-feedstock/pull/5
