### ISSUE TITLE
Missing headers for version 0.77?

### ISSUE THREAD

**Issue by james-d-mitchell** [conda-forge/bliss-feedstock#6]
### Comment:

@saraedum @isuruf It seems like some of the headers are missing when `bliss` 0.77 is installed by conda. For example, the header `bliss_C.h` is not installed in `micromamba/envs/digraph/include/bliss/` but it exists in the release tarball of bliss. 
This means we can no longer use the conda version of `bliss` in the `Digraphs` package for GAP, as per:

https://github.com/digraphs/Digraphs/actions/runs/7422806823/job/20198886373?pr=597

Maybe I'm doing something wrong, happy to be told about it if I am.

**Comment by saraedum** [comment]
This was fixed in #7.
